AWSTemplateFormatVersion: "2010-09-09"
Description: 'Testing Cloud Formation'

Parameters:
  BucketName:
    Description: raw_bucket
    Type: String
    Default: my-raw-bucket-bruno-testingx7k2

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName